service: trello-sb-chart-automation
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

provider:
  name: aws
  runtime: python3
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess'
    - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
    - 'arn:aws:iam::aws:policy/AWSLambdaExecute'

functions:
  trelloSprintBurndown:
    handler: handler.trelloSprintBurndown
    description: Creates Sprint Burndown Chart in Trello Board
    runtime: python3.8
    memorySize: 512
    timeout: 120
    environment:
      BAMBOOHR_API_TOKEN_SSM_PARAMETER_KEY: '/Serverless/BambooHR/ApiToken'
      TRELLO_API_KEY_SSM_PARAMETER_KEY: '/Serverless/Trello/ApiKey'
      TRELLO_TOKEN_SSM_PARAMETER_KEY: '/Serverless/Trello/Token'
      TRELLO_ORGANIZATION_ID: ${env:TRELLO_ORGANIZATION_ID}
      POWERUP_NAME: ${env:POWERUP_NAME}
      BAMBOOHR_ORG_NAME: ${env:BAMBOOHR_ORG_NAME}
      CALLBACK_URL: 
        Fn::Sub: 'https://#{ApiGatewayRestApi}.execute-api.#{AWS::Region}.amazonaws.com/${self:provider.stage}/${env:API_PATH}'
    events:
      - http:
          path: ${env:API_PATH}
          integration: mock
          method: head
          request:
            template:
              application/json: '{"statusCode": 200}'
          response:
            template: $input.path('$')
            statusCodes:
              200:
                pattern: ''
      - http:
          path: ${env:API_PATH}
          integration: lambda
          method: post
          async: true
          request:
            template:
              application/json: >
                {
                  "x_trello_webhook": "$util.escapeJavaScript($input.params().header.get('X-Trello-Webhook'))",
                  "payload": "$util.escapeJavaScript($input.body)"
                }
    tags:
      ManagedBy: "Serverless"

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
